// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-nD5fqSsOWXOKgRS3smx1x3rlDboTHuE',
    appId: '1:310616988526:web:530d9f01deb88156dfff7f',
    messagingSenderId: '310616988526',
    projectId: 'travelassist-1',
    authDomain: 'travelassist-1.firebaseapp.com',
    storageBucket: 'travelassist-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFcZiY0lOHoCVz_QRVtKNn9w8ayXJNN8',
    appId: '1:310616988526:android:bf5c0748eb554e6edfff7f',
    messagingSenderId: '310616988526',
    projectId: 'travelassist-1',
    storageBucket: 'travelassist-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaQKF4bWC3VJ7stjLBXNFx9OY6gj2GRBo',
    appId: '1:310616988526:ios:aaa04c6e44cd6c3adfff7f',
    messagingSenderId: '310616988526',
    projectId: 'travelassist-1',
    storageBucket: 'travelassist-1.firebasestorage.app',
    iosBundleId: 'com.example.travelAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaQKF4bWC3VJ7stjLBXNFx9OY6gj2GRBo',
    appId: '1:310616988526:ios:aaa04c6e44cd6c3adfff7f',
    messagingSenderId: '310616988526',
    projectId: 'travelassist-1',
    storageBucket: 'travelassist-1.firebasestorage.app',
    iosBundleId: 'com.example.travelAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-nD5fqSsOWXOKgRS3smx1x3rlDboTHuE',
    appId: '1:310616988526:web:90e8fdc8618f287adfff7f',
    messagingSenderId: '310616988526',
    projectId: 'travelassist-1',
    authDomain: 'travelassist-1.firebaseapp.com',
    storageBucket: 'travelassist-1.firebasestorage.app',
  );
}
